### ISSUE TITLE
Task :tensorflow:cinteropCocoapodTFLTensorFlowLiteIosArm64 FAILED

### ISSUE THREAD

**Issue by CloverRedspot** [icerockdev/moko-tensorflow#10]
Hi.
I am getting this exception during the build of this project. 
Do you have any idea what went wrong?
Any help would be greatly appreciated.

IntelliJ 2022.1.3
kotlin 1.7.0

```
> Task :tensorflow:cinteropCocoapodTFLTensorFlowLiteIosArm64 FAILED
Exception in thread "main" java.lang.Error: /var/folders/sb/gn7xgpbj0vg3fbrqdg2ph66h0000gn/T/8487972035033938931.m:1:9: fatal error: could not build module 'TFLTensorFlowLite'
        at org.jetbrains.kotlin.native.interop.indexer.UtilsKt.ensureNoCompileErrors(Utils.kt:152)
        at org.jetbrains.kotlin.native.interop.indexer.ModuleSupportKt.getModulesASTFiles(ModuleSupport.kt:68)
        at org.jetbrains.kotlin.native.interop.indexer.ModuleSupportKt.getModulesInfo(ModuleSupport.kt:14)
        at org.jetbrains.kotlin.native.interop.gen.jvm.MainKt.buildNativeLibrary(main.kt:515)
        at org.jetbrains.kotlin.native.interop.gen.jvm.MainKt.processCLib(main.kt:266)
        at org.jetbrains.kotlin.native.interop.gen.jvm.MainKt.interop(main.kt:76)
        at org.jetbrains.kotlin.cli.utilities.InteropCompilerKt.invokeInterop(InteropCompiler.kt:45)
        at org.jetbrains.kotlin.cli.utilities.MainKt.mainImpl(main.kt:38)
        at org.jetbrains.kotlin.cli.utilities.MainKt.main(main.kt:60)

> Task :cocoapodBuildTFLTensorFlowLiteIphonesimulatorX86_64
xcodebuild result is 0

FAILURE: Build failed with an exception.
```

**Comment by Alex009** [comment]
at first recommend you to try build all cocoapods via xcode. maybe current xcode not works with this TF version.
also maybe something in kotlin 1.7.0 broken in cinterop. try 1.7.10 or 1.6.21 versions

**Comment by MohamadJaara** [comment]
@CloverRedspot I wonder if you were able to solve the problem?

**Comment by shadmanadman** [comment]
Please refer to this library as it's fresh and improved:
https://github.com/shadmanadman/kflite
